events {
  worker_connections 1024;
}

http {
  server {
    listen 80;
    server_name localhost;

    location /grafana/ {
      proxy_pass http://grafana:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /rabbitmq/ {
      proxy_pass http://rabbitmq:15672/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /auth/ {
      proxy_pass http://identity:8080/auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /.well-known/ {
      proxy_pass http://identity:8080/.well-known/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/livestreams/ {
      proxy_pass http://livestream:8080/api/livestreams/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/classes/ {
      proxy_pass http://classes:8080/api/classes/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/trainers/ {
      proxy_pass http://trainer:8080/api/trainers/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /workout/ {
      proxy_pass http://traininglog:8080/workout/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
      return 200 'ok';
      add_header Content-Type text/plain;
    }

    location / {
      proxy_pass http://frontend:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_intercept_errors on;
      error_page 404 = /index.html;
    }
  }
}
