events {
  worker_connections 1024;
}

http {
  server {
    listen 80;
    server_name localhost;

    location /auth/ {
      proxy_pass http://identity:8080/auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /.well-known/ {
      proxy_pass http://identity:8080/.well-known/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location /identity/healthz {
      proxy_pass http://identity:8080/healthz;
      proxy_set_header Host $host;
    }

    location / {
      return 200 'Fitlife nginx is running';
      add_header Content-Type text/plain;
    }
  }
}
