name: Deploy to Server

on:
  workflow_dispatch:
  push:
    branches: [main, master]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Log ind på DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull newest images
        run: docker compose pull

      - name: Restart containers
        env:
          RABBITMQ_USER: ${{ secrets.RABBITMQ_USER }}
          RABBITMQ_PASSWORD: ${{ secrets.RABBITMQ_PASSWORD }}
          MONGO_ROOT_USER: ${{ secrets.MONGO_ROOT_USER }}
          MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
          GRAFANA_ADMIN_USER: ${{ secrets.GRAFANA_ADMIN_USER }}
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
          IDENTITY_JWT_RSA_PRIVATE_KEY: ${{ secrets.IDENTITY_JWT_RSA_PRIVATE_KEY }}
        run: docker compose up -d --remove-orphans
